- go.mod
- go.sum
- internal/commands/push.go
- internal/commands/validate.go
- internal/model/id.go
- internal/model/id_test.go
- internal/model/model.go
- internal/remotes/fs.go
- internal/remotes/remote.go
- feat: add automatic generation of ids and comparison with existing versions on push
> feat: add automatic generation of ids and comparison with existing versions on push

- go.mod
- go.sum
- internal/commands/push.go
- internal/commands/validate.go
- internal/model/id.go
- internal/model/id_test.go
- internal/model/model.go
- internal/validation/validate.go
- feat: sanitize manufacturer, author, mpn for use in file names
> feat: sanitize manufacturer, author, mpn for use in file names

- internal/commands/push.go
- internal/commands/push_test.go
- internal/validation/validate_test.go
- feat: implement moving original id to links; add some tests
> feat: implement moving original id to links; add some tests

- cmd/push.go
- internal/commands/push.go
- internal/commands/push_test.go
- internal/util.go
- feat: push an entire directory recursively 
- feat: add flags for specifying optional path parts
> feat: push an entire directory recursively

- internal/remotes/fs.go
- main.go
- chore: add a config search path in home dir
> chore: add a config search path in home dir

- internal/commands/push.go
- internal/commands/push_test.go
- internal/remotes/fs.go
- internal/remotes/fs_test.go
- internal/remotes/remote.go
- internal/util.go
- test/data/push/omnilamp-versioned.json
- test/data/push/omnilamp.json
> test: add tests for push

- internal/commands/push.go
- internal/commands/push_test.go
- fix: fix incorrect sanitizing of optional path parts on Windows
fixes #32
> fix: fix incorrect sanitizing of optional path parts on Windows

- cmd/push.go
- fixup: fix push command's usage message
> fixup: fix push command's usage message

- cmd/fetch.go
- cmd/push.go
- internal/app/cli/fetch.go
- internal/app/http/facade.go
- internal/commands/fetch.go
- internal/commands/fetch_test.go
- internal/remotes/fs.go
- internal/remotes/fs_test.go
- internal/remotes/http.go
- internal/remotes/mocks/Remote.go
- internal/remotes/remote.go
- feat: add option to CLI fetch to redirect output to a file, optionally create a folder structure
> feat: add option to CLI fetch to redirect output to a file

- cmd/fetch.go
- internal/app/cli/fetch.go
- internal/app/cli/fetch_test.go
- test: add test for cli fetch command options
> test: add test for cli fetch command options

- internal/remotes/http_test.go
- test: add test for HttpRemote.Fetch
> test: add test for HttpRemote.Fetch

- internal/app/http/handler.go
- internal/app/http/handler_test.go
- fix: generate relative links to thing models without extra "../"
> fix: generate relative links to thing models without extra ..

- cmd/remote/remote_set_auth.go
- internal/app/cli/remote.go
- feat: add command "remote set-auth"
> feat: add command "remote set-auth"

- api/tm-catalog.openapi.yaml
- internal/app/http/common.go
- internal/app/http/handler.go
- internal/app/http/models.gen.go
- internal/app/http/server.gen.go
Changes:
+ API
+ renamed query parameter `search.content` to `search`
> refactor(api): renamed param search.content to search

- .github/workflows/go.yml
- api/tm-catalog.openapi.yaml
Changes:
+ added openapi linting (spectral) to pipeline
> chore: openapi lint in pipeline

- CHANGELOG.md
- api/tm-catalog.openapi.yaml
- cmd/fetch.go
- cmd/pull.go
- internal/app/cli/fetch.go
- internal/app/cli/fetch_test.go
- internal/app/cli/pull.go
- internal/app/cli/pull_test.go
- internal/app/http/handler.go
- internal/app/http/handler_test.go
- internal/app/http/mock_HandlerService.go
- internal/app/http/server/models.gen.go
- internal/app/http/server/server.gen.go
- internal/app/http/service.go
- internal/app/http/service_test.go
- internal/commands/fetch.go
- internal/commands/fetch_test.go
- internal/utils/util.go
- feat: add flag to fetch to restore original external id
> feat: add flag to fetch to restore original external id

- .github/workflows/go.yml
- build/list-dependencies.sh
Changes:
+ added script to list dependencies from compiled binaries (can be used local or in pipeline)
+ added list dependencies to pipeline output
> chore: list dependencies

- internal/model/toc.go
- internal/remotes/fs.go
- internal/remotes/fs_test.go
- internal/remotes/union.go
- internal/testutils/os_helpers.go
- fix: fix updating of toc on tm delete when remote is referred by a relative path
> fix: fix updating of toc on tm delete when remote is referred by a relative path

- go.mod
- go.sum
- internal/app/cli/push_test.go
- internal/commands/push.go
- internal/commands/validate/validate.go
- internal/commands/validate/validate_test.go
- internal/utils/util.go
- internal/utils/util_test.go
Changes:
+ replacing github.com/kennygrant/sanitize by own implementation
+ converting a name always to lowercase when sanitize
> refactor: sanitize

- CHANGELOG.md
- api/tm-catalog.openapi.yaml
- cmd/attachment/attachment.go
- internal/app/http/handler.go
- internal/app/http/handler_test.go
- internal/app/http/mapping.go
- internal/app/http/server/models.gen.go
- internal/app/http/server/server.gen.go
- internal/model/mapping.go
- internal/repos/tmc_test.go
This reverts commit b58d4fe1cca14f421867ef975e742a71a455adf0.
> Revert "temp: comment out attachment functionality"

- CHANGELOG.md
- feat: reorganize repo config editing subcommands
- feat: add http basic auth for file and tmc repos
- feat: add fixed request headers for tmc and file repos
> feat: repo config subcommands, http basic auth, fixed headers

- README.md
- docs/_pages/10-installation.md
Just a small documentation fix
> Bumping release version in readme and pages

- api/tm-catalog.openapi.yaml
> Fix: API description mentions writeonly
